[package]
name = "aoc"
version = "0.1.0"
authors = ["Paul Seehofer <seehofer.paul@gmail.com>"]

[dependencies]


[[bin]]
name = "day1"
path = "src/day1_main.rs"

[[bin]]
name = "day2"
path = "src/day2_main.rs"

[[bin]]
name = "day3"
path = "src/day3_main.rs"